    <div class="row">
        
        <div class="col-md-6">

            <div class="row">
                <div class="col-md-4">
                    <div class="content-box bg-blue">
                        <div class="content-box-wrapper">
                            <div class="chart-home" data-percent="55">
                                <span>55</span>%
                            </div>
                            <div class="text-center pad10T font-size-13 font-white opacity-80 text-transform-upr">New visits</div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="content-box bg-orange">
                        <div class="content-box-wrapper">
                            <div class="chart-home" data-percent="46">
                                <span>46</span>%
                            </div>
                            <div class="text-center pad10T font-size-13 font-white opacity-80 text-transform-upr">Bounce rate</div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="content-box bg-green">
                        <div class="content-box-wrapper">
                            <div class="chart-home" data-percent="92">
                                <span>92</span>%
                            </div>
                            <div class="text-center pad10T font-size-13 font-white opacity-80 text-transform-upr">Server load</div>
                        </div>
                    </div>
                </div>
            </div>

            <ul class="list-group row list-group-icons">

                <li class="col-md-6">
                    <a href="#" class="list-group-item">
                        <i class="glyph-icon font-red icon-bullhorn"></i>
                        Profile
                    </a>
                </li>
                <li class="col-md-6">
                    <a href="#" class="list-group-item">
                        <i class="glyph-icon font-primary icon-camera"></i>
                        Messages
                    </a>
                </li>
            </ul>

            <table class="table mrg25T text-center">
                <tbody>
                <tr>
                    <td class="remove-border">1</td>
                    <td class="remove-border font-bold text-left">John Clark</td>
                    <td class="remove-border text-left"><a href="#" title="">Support</a></td>
                    <td class="remove-border"><div class="bs-label bg-orange">+152</div></td>
                    <td class="remove-border text-right hidden-mobile">
                        <div class="dropdown">
                            <a href="#" title="" class="btn btn-md btn-default" data-toggle="dropdown">
                                    <span class="button-content">
                                        <i class="glyph-icon font-size-11 icon-cog"></i>
                                        <i class="glyph-icon font-size-11 icon-chevron-down"></i>
                                    </span>
                            </a>
                            <ul class="dropdown-menu float-right">

                                <li>
                                    <a href="#" title="">
                                        <i class="glyph-icon icon-edit mrg5R"></i>
                                        Edit
                                    </a>
                                </li>
                                <li>
                                    <a href="#" title="">
                                        <i class="glyph-icon icon-calendar mrg5R"></i>
                                        Schedule
                                    </a>
                                </li>
                                <li>
                                    <a href="#" title="">
                                        <i class="glyph-icon icon-download mrg5R"></i>
                                        Download
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#" class="font-red" title="">
                                        <i class="glyph-icon icon-remove mrg5R"></i>
                                        Delete
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>2</td>
                    <td class="font-bold text-left">Kenny Davis</td>
                    <td class="text-left"><a href="#" title="">Business management</a></td>
                    <td><div class="bs-label bg-black">+152</div></td>
                    <td class="text-right hidden-mobile">
                        <div class="dropdown">
                            <a href="#" title="" class="btn btn-md btn-default" data-toggle="dropdown">
                                    <span class="button-content">
                                        <i class="glyph-icon font-size-11 icon-cog"></i>
                                        <i class="glyph-icon font-size-11 icon-chevron-down"></i>
                                    </span>
                            </a>
                            <ul class="dropdown-menu float-right">

                                <li>
                                    <a href="#" title="">
                                        <i class="glyph-icon icon-edit mrg5R"></i>
                                        Edit
                                    </a>
                                </li>
                                <li>
                                    <a href="#" title="">
                                        <i class="glyph-icon icon-calendar mrg5R"></i>
                                        Schedule
                                    </a>
                                </li>
                                <li>
                                    <a href="#" title="">
                                        <i class="glyph-icon icon-download mrg5R"></i>
                                        Download
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#" class="font-red" title="">
                                        <i class="glyph-icon icon-remove mrg5R"></i>
                                        Delete
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>3</td>
                    <td class="font-bold text-left">David Robertson</td>
                    <td class="text-left"><a href="#" title="">Sales</a></td>
                    <td><div class="bs-label bg-green">+191</div></td>
                    <td class="text-right hidden-mobile">
                        <div class="dropdown">
                            <a href="#" title="" class="btn btn-md btn-default" data-toggle="dropdown">
                                    <span class="button-content">
                                        <i class="glyph-icon font-size-11 icon-cog"></i>
                                        <i class="glyph-icon font-size-11 icon-chevron-down"></i>
                                    </span>
                            </a>
                            <ul class="dropdown-menu float-right">

                                <li>
                                    <a href="#" title="">
                                        <i class="glyph-icon icon-edit mrg5R"></i>
                                        Edit
                                    </a>
                                </li>
                                <li>
                                    <a href="#" title="">
                                        <i class="glyph-icon icon-calendar mrg5R"></i>
                                        Schedule
                                    </a>
                                </li>
                                <li>
                                    <a href="#" title="">
                                        <i class="glyph-icon icon-download mrg5R"></i>
                                        Download
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#" class="font-red" title="">
                                        <i class="glyph-icon icon-remove mrg5R"></i>
                                        Delete
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>4</td>
                    <td class="font-bold text-left">John Doe</td>
                    <td class="text-left"><a href="#" title="">Business</a></td>
                    <td><div class="bs-label bg-red">+483</div></td>
                    <td class="text-right hidden-mobile">
                        <div class="dropdown">
                            <a href="#" title="" class="btn btn-md btn-default" data-toggle="dropdown">
                                    <span class="button-content">
                                        <i class="glyph-icon font-size-11 icon-cog"></i>
                                        <i class="glyph-icon font-size-11 icon-chevron-down"></i>
                                    </span>
                            </a>
                            <ul class="dropdown-menu float-right">

                                <li>
                                    <a href="#" title="">
                                        <i class="glyph-icon icon-edit mrg5R"></i>
                                        Edit
                                    </a>
                                </li>
                                <li>
                                    <a href="#" title="">
                                        <i class="glyph-icon icon-calendar mrg5R"></i>
                                        Schedule
                                    </a>
                                </li>
                                <li>
                                    <a href="#" title="">
                                        <i class="glyph-icon icon-download mrg5R"></i>
                                        Download
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="#" class="font-red" title="">
                                        <i class="glyph-icon icon-remove mrg5R"></i>
                                        Delete
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <div class="content-box border-top border-green">
                        <h3 class="content-box-header clearfix">
                            Sales statistics
                            <small>(12 July 2014 - 19 October 2014)</small>
                            <span class="btn-group btn-group-sm float-right" data-toggle="buttons">
                                <span class="btn btn-black">
                                    <input type="radio" name="test-toggle-radio">
                                    <i class="glyph-icon icon-edit"></i>
                                </span>
                                <span class="btn btn-black">
                                    <input type="radio" name="test-toggle-radio">
                                    <i class="glyph-icon icon-bar-chart-o"></i>
                                </span>
                            </span>
                        </h3>
                        <div class="content-box-wrapper">
                            <div id="hero-area" style="width: 100%;" class="graph"></div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="content-box bg-white post-box">
                <textarea name="" class="textarea-autosize" placeholder="What are you doing right now?"></textarea>
                <div class="button-pane">
                    <a href="#" class="btn btn-md btn-link hover-white" title="">
                        <i class="glyph-icon icon-volume-down"></i>
                    </a>
                    <a href="#" class="btn btn-md btn-link hover-white" title="">
                        <i class="glyph-icon icon-video-camera"></i>
                    </a>
                    <a href="#" class="btn btn-md btn-link hover-white" title="">
                        <i class="glyph-icon icon-microphone"></i>
                    </a>
                    <a href="#" class="btn btn-md btn-link hover-white" title="">
                        <i class="glyph-icon icon-picture-o"></i>
                    </a>

                    <a href="#" class="btn btn-md btn-post float-right btn-success" title="">
                        Share it!
                    </a>

                </div>
            </div>

          


        </div>

    </div>

<!--[if gte IE 9]>

    <!-- Morris charts -->

    <script type="text/javascript" src="<?php echo $this->basePath() ?>/admin/assets-minified/js-core/raphael.js"></script>
    <!--<link rel="stylesheet" type="text/css" href="assets-minified/widgets/charts/morris/morris.css">-->
    <script type="text/javascript" src="<?php echo $this->basePath() ?>/admin/assets-minified/widgets/charts/morris/morris.js"></script>


    <script type="text/javascript">

        $(function () {

            Morris.Area({
                element: 'hero-area',
                data: [
                    { y: '2006', a: 90, b: 76 },
                    { y: '2007', a: 75,  b: 65 },
                    { y: '2008', a: 50,  b: 40 },
                    { y: '2009', a: 75,  b: 65 },
                    { y: '2010', a: 50,  b: 40 },
                    { y: '2011', a: 75,  b: 65 },
                    { y: '2012', a: 25, b: 20 }
                ],
                xkey: 'y',
                ykeys: ['a', 'b'],
                labels: ['Series A', 'Series B'],
                pointSize: 4,
                hideHover: 'auto',
                fillOpacity: 0.03,
                lineColors: ['#768294','#0084ff']
            });
        });

    </script>
<![endif]-->