<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Faktoria '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/admin/assets-minified/all-demo.css')
                        ->prependStylesheet($this->basePath() . '/admin/bootstrap-table/dist/bootstrap-table.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/admin/assets-minified/js-core.js',   'text/javascript')
         ?>

         <script type="text/javascript">
            $(window).load(function(){
                setTimeout(function() {
                    $('#loading').fadeOut( 400, "linear" );
                }, 300);
            });
        </script>
        <style>
            #loading {position: fixed;width: 100%;height: 100%;left: 0;top: 0;right: 0;bottom: 0;display: block;background: #fff;z-index: 10000;}
            #loading img {position: absolute;top: 50%;left: 50%;margin: -23px 0 0 -23px;}
        </style>

    </head>
    <body>
        <div id="loading"><img src="<?php echo $this->basePath() ?>/assets/images/spinner/loader-dark.gif" alt="Loading..."></div>        
         <div id="sb-site">
            <div id="page-wrapper">
                <div id="page-header" class="clearfix">
                    <div id="header-logo" class="rm-transition">
                        <a href="#" class="tooltip-button hidden-desktop" title="Navigation Menu" id="responsive-open-menu">
                            <i class="glyph-icon icon-align-justify"></i>
                        </a>
                        <span>La Faktoria <i class="opacity-80">1.0</i>
                        </span>

                        <a id="collapse-sidebar" href="#" title="">
                            <i class="glyph-icon icon-chevron-left"></i>
                        </a>
                    </div>
                    <!-- #header-logo -->

                    <div id="header-left">

                        <div class="dropdown">

                            <a data-toggle="dropdown" href="#" title="">
                                <span class="bs-badge badge-absolute bg-orange">5</span>
                                <i class="glyph-icon icon-bell"></i>
                            </a>
                            <div class="dropdown-menu">

                                <div class="popover-title display-block clearfix pad10A">
                                    Notifications
                                </div>
                                <div class="scrollable-content scrollable-nice box-md scrollable-small">

                                    <ul class="no-border notifications-box">
                                        <li>
                                            <span class="bg-danger icon-notification glyph-icon icon-bullhorn"></span>
                                            <span class="notification-text">This is an error notification</span>
                                            <div class="notification-time">
                                                a few seconds ago
                                                <span class="glyph-icon icon-clock-o"></span>
                                            </div>
                                        </li>
                                        <li>
                                            <span class="bg-warning icon-notification glyph-icon icon-users"></span>
                                            <span class="notification-text font-blue">This is a warning notification</span>
                                            <div class="notification-time">
                                                <b>15</b> minutes ago
                                                <span class="glyph-icon icon-clock-o"></span>
                                            </div>
                                        </li>
                                        <li>
                                            <span class="bg-green icon-notification glyph-icon icon-sitemap"></span>
                                            <span class="notification-text font-green">A success message example.</span>
                                            <div class="notification-time">
                                                <b>2 hours</b> ago
                                                <span class="glyph-icon icon-clock-o"></span>
                                            </div>
                                        </li>
                                        <li>
                                            <span class="bg-azure icon-notification glyph-icon icon-random"></span>
                                            <span class="notification-text">This is an error notification</span>
                                            <div class="notification-time">
                                                a few seconds ago
                                                <span class="glyph-icon icon-clock-o"></span>
                                            </div>
                                        </li>
                                        <li>
                                            <span class="bg-warning icon-notification glyph-icon icon-ticket"></span>
                                            <span class="notification-text">This is a warning notification</span>
                                            <div class="notification-time">
                                                <b>15</b> minutes ago
                                                <span class="glyph-icon icon-clock-o"></span>
                                            </div>
                                        </li>
                                        <li>
                                            <span class="bg-blue icon-notification glyph-icon icon-user"></span>
                                            <span class="notification-text font-blue">Alternate notification styling.</span>
                                            <div class="notification-time">
                                                <b>2 hours</b> ago
                                                <span class="glyph-icon icon-clock-o"></span>
                                            </div>
                                        </li>
                                        <li>
                                            <span class="bg-purple icon-notification glyph-icon icon-user"></span>
                                            <span class="notification-text">This is an error notification</span>
                                            <div class="notification-time">
                                                a few seconds ago
                                                <span class="glyph-icon icon-clock-o"></span>
                                            </div>
                                        </li>
                                        <li>
                                            <span class="bg-warning icon-notification glyph-icon icon-user"></span>
                                            <span class="notification-text">This is a warning notification</span>
                                            <div class="notification-time">
                                                <b>15</b> minutes ago
                                                <span class="glyph-icon icon-clock-o"></span>
                                            </div>
                                        </li>
                                        <li>
                                            <span class="bg-green icon-notification glyph-icon icon-user"></span>
                                            <span class="notification-text font-green">A success message example.</span>
                                            <div class="notification-time">
                                                <b>2 hours</b> ago
                                                <span class="glyph-icon icon-clock-o"></span>
                                            </div>
                                        </li>
                                        <li>
                                            <span class="bg-purple icon-notification glyph-icon icon-user"></span>
                                            <span class="notification-text">This is an error notification</span>
                                            <div class="notification-time">
                                                a few seconds ago
                                                <span class="glyph-icon icon-clock-o"></span>
                                            </div>
                                        </li>
                                        <li>
                                            <span class="bg-warning icon-notification glyph-icon icon-user"></span>
                                            <span class="notification-text">This is a warning notification</span>
                                            <div class="notification-time">
                                                <b>15</b> minutes ago
                                                <span class="glyph-icon icon-clock-o"></span>
                                            </div>
                                        </li>
                                    </ul>

                                </div>
                                <div class="pad10A button-pane button-pane-alt text-center">
                                    <a href="#" class="btn btn-primary" title="View all notifications">
                                        View all notifications
                                    </a>
                                </div>

                            </div>
                        </div>

                        <div class="dropdown">

                            <a data-toggle="dropdown" href="#" title="">
                                <span class="bs-badge badge-absolute bg-red">2</span>
                                <i class="glyph-icon icon-tasks"></i>
                            </a>
                            <div class="dropdown-menu pad0A" id="progress-dropdown">

                                <div class="scrollable-content scrollable-nice box-sm scrollable-small">

                                    <ul class="no-border progress-box progress-box-links">
                                        <li>
                                            <a href="#" title="">
                                                <div class="progress-title">
                                                    Finishing uploading files
                                                    <b>23%</b>
                                                </div>
                                                <div class="progressbar-smaller progressbar" data-value="23">
                                                    <div class="progressbar-value bg-blue-alt">
                                                        <div class="progressbar-overlay"></div>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" title="">
                                                <div class="progress-title">
                                                    Roadmap progress
                                                    <b>91%</b>
                                                </div>
                                                <div class="progressbar-smaller progressbar" data-value="91">
                                                    <div class="progressbar-value bg-red">
                                                        <div class="progressbar-overlay"></div>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" title="">
                                                <div class="progress-title">
                                                    Images upload
                                                    <b>58%</b>
                                                </div>
                                                <div class="progressbar-smaller progressbar" data-value="58">
                                                    <div class="progressbar-value bg-green"></div>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" title="">
                                                <div class="progress-title">
                                                    WordPress migration
                                                    <b>74%</b>
                                                </div>
                                                <div class="progressbar-smaller progressbar" data-value="74">
                                                    <div class="progressbar-value bg-purple"></div>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" title="">
                                                <div class="progress-title">
                                                    Agile development procedures
                                                    <b>91%</b>
                                                </div>
                                                <div class="progressbar-smaller progressbar" data-value="91">
                                                    <div class="progressbar-value bg-black">
                                                        <div class="progressbar-overlay"></div>
                                                    </div>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" title="">
                                                <div class="progress-title">
                                                    Systems integration
                                                    <b>58%</b>
                                                </div>
                                                <div class="progressbar-smaller progressbar" data-value="58">
                                                    <div class="progressbar-value bg-azure"></div>
                                                </div>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#" title="">
                                                <div class="progress-title">
                                                    Code optimizations
                                                    <b>97%</b>
                                                </div>
                                                <div class="progressbar-smaller progressbar" data-value="97">
                                                    <div class="progressbar-value bg-yellow"></div>
                                                </div>
                                            </a>
                                        </li>
                                    </ul>

                                </div>
                                <div class="pad5A button-pane button-pane-alt text-center">
                                    <a href="#" class="btn display-block font-normal hover-green" title="View all notifications">
                                        View all notifications
                                    </a>
                                </div>

                            </div>
                        </div>

                        <div class="dropdown">
                            <a href="#" data-toggle="dropdown" data-placement="left" class="popover-button-header tooltip-button" title="Example menu">
                                <span class="bs-badge badge-absolute bg-green">9</span>
                                <i class="glyph-icon icon-th"></i>
                            </a>
                            <div class="dropdown-menu">
                                <div class="box-sm">
                                    <div class="pad5T pad10B pad10L pad10R dashboard-buttons clearfix">
                                        <a href="#" class="btn vertical-button hover-blue-alt" title="">
                                                <span class="glyph-icon icon-separator-vertical pad0A medium">
                                                    <i class="glyph-icon icon-dashboard opacity-80 font-size-20"></i>
                                                </span>
                                            Dashboard
                                        </a>
                                        <a href="#" class="btn vertical-button hover-green" title="">
                                                <span class="glyph-icon icon-separator-vertical pad0A medium">
                                                    <i class="glyph-icon icon-tags opacity-80 font-size-20"></i>
                                                </span>
                                            Widgets
                                        </a>
                                        <a href="#" class="btn vertical-button hover-orange" title="">
                                                <span class="glyph-icon icon-separator-vertical pad0A medium">
                                                    <i class="glyph-icon icon-fire opacity-80 font-size-20"></i>
                                                </span>
                                            Tables
                                        </a>
                                        <a href="#" class="btn vertical-button hover-orange" title="">
                                                <span class="glyph-icon icon-separator-vertical pad0A medium">
                                                    <i class="glyph-icon icon-bar-chart-o opacity-80 font-size-20"></i>
                                                </span>
                                            Charts
                                        </a>
                                        <a href="#" class="btn vertical-button hover-purple" title="">
                                                <span class="glyph-icon icon-separator-vertical pad0A medium">
                                                    <i class="glyph-icon icon-laptop opacity-80 font-size-20"></i>
                                                </span>
                                            Buttons
                                        </a>
                                        <a href="#" class="btn vertical-button hover-azure" title="">
                                                <span class="glyph-icon icon-separator-vertical pad0A medium">
                                                    <i class="glyph-icon icon-code opacity-80 font-size-20"></i>
                                                </span>
                                            Panels
                                        </a>
                                    </div>

                                    <div class="bg-gray text-transform-upr font-size-12 font-gray-dark pad10A">Dashboard menu</div>
                                    <div class="pad5T pad10B pad10L pad10R dashboard-buttons clearfix">
                                        <a href="#" class="btn vertical-button remove-border btn-info" title="">
                                                <span class="glyph-icon icon-separator-vertical pad0A medium">
                                                    <i class="glyph-icon icon-dashboard opacity-80 font-size-20"></i>
                                                </span>
                                            Dashboard
                                        </a>
                                        <a href="#" class="btn vertical-button remove-border btn-danger" title="">
                                                <span class="glyph-icon icon-separator-vertical pad0A medium">
                                                    <i class="glyph-icon icon-tags opacity-80 font-size-20"></i>
                                                </span>
                                            Widgets
                                        </a>
                                        <a href="#" class="btn vertical-button remove-border btn-purple" title="">
                                                <span class="glyph-icon icon-separator-vertical pad0A medium">
                                                    <i class="glyph-icon icon-fire opacity-80 font-size-20"></i>
                                                </span>
                                            Tables
                                        </a>
                                        <a href="#" class="btn vertical-button remove-border btn-azure" title="">
                                                <span class="glyph-icon icon-separator-vertical pad0A medium">
                                                    <i class="glyph-icon icon-bar-chart-o opacity-80 font-size-20"></i>
                                                </span>
                                            Charts
                                        </a>
                                        <a href="#" class="btn vertical-button remove-border btn-yellow" title="">
                                                <span class="glyph-icon icon-separator-vertical pad0A medium">
                                                    <i class="glyph-icon icon-laptop opacity-80 font-size-20"></i>
                                                </span>
                                            Buttons
                                        </a>
                                        <a href="#" class="btn vertical-button remove-border btn-warning" title="">
                                                <span class="glyph-icon icon-separator-vertical pad0A medium">
                                                    <i class="glyph-icon icon-code opacity-80 font-size-20"></i>
                                                </span>
                                            Panels
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div id="header-right">
                        <div class="user-profile dropdown">
                            <a href="#" title="" class="user-ico clearfix" data-toggle="dropdown">
                                <img width="36" class="img-rounded" src="<?php echo $this->basePath() ?>/assets/dummy-images/gravatar.jpg" alt="">
                                <span><?php $user = $this->identity(); echo $this->escapeHtml($user->full_name);?></span>
                                <i class="glyph-icon icon-chevron-down"></i>
                            </a>
                            <div class="dropdown-menu pad0B float-right">
                                <div class="box-sm">
                                    <div class="login-box clearfix">
                                        <div class="user-img">
                                            <a href="#" title="" class="change-img">Change photo</a>
                                            <img src="<?php echo $this->basePath()?>/assets/dummy-images/gravatar.jpg" alt="">
                                        </div>
                                        <div class="user-info">
                                        <span>
                                            Horia Simon
                                            <i>Front-end web developer</i>
                                        </span>
                                            <a href="#" title="">Edit profile</a>
                                            <a href="#" title="">View notifications</a>
                                        </div>
                                    </div>
                                    <div class="divider"></div>
                                    <ul class="reset-ul mrg5B">
                                        <li>
                                            <a href="#">
                                                View login page example
                                                <i class="glyph-icon float-right icon-caret-right"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                View lockscreen example
                                                <i class="glyph-icon float-right icon-caret-right"></i>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                View account details
                                                <i class="glyph-icon float-right icon-caret-right"></i>
                                            </a>
                                        </li>
                                    </ul>
                                    <div class="pad5A button-pane button-pane-alt text-center">
                                        <a href="/dashboard/logout" class="btn display-block font-normal btn-danger">
                                            <i class="glyph-icon icon-power-off"></i>
                                            Logout
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div id="page-nav-right">
                            <a href="#" title="" class="btn sb-open-right no-shadow updateEasyPieChart">
                                <i class="glyph-icon icon-cogs"></i>
                                Statistics
                            </a>
                            <a href="#" title="" class="btn sb-open-left no-shadow updateEasyPieChart">
                                <i class="glyph-icon icon-comment"></i>
                                Chat
                            </a>
                        </div>

                    </div>
                </div>
                <!-- #page-header -->

                <div id="page-sidebar" class="rm-transition">
                    <div id="page-sidebar-wrapper">

                        <?php
                            echo $this->navigation('navigation')
                                      ->menu()
                                      ->setPartial('layout/menu')
                                      ->render();
                        ?>

                        <div class="divider"></div>

                        <div class="hidden-mobile text-center mrg15A">
                            <div class="btn-group btn-group-sm">
                                <a href="javascript:;" class="btn btn-primary tooltip-button" data-placement="top" title="Top tooltip">
                                    <i class="glyph-icon icon-flag"></i>
                                </a>
                                <a href="javascript:;" class="btn btn-primary tooltip-button" data-placement="bottom" title="Bottom tooltip">
                                    <i class="glyph-icon icon-inbox"></i>
                                </a>
                                <a href="javascript:;" class="btn btn-primary tooltip-button" data-placement="right" title="Right tooltip">
                                    <i class="glyph-icon icon-hdd-o"></i>
                                </a>
                            </div>
                        </div>

                        <div class="divider"></div>
                    </div><!-- #page-sidebar-wrapper -->
                </div><!-- #page-sidebar -->

                <div id="page-content-wrapper" class="rm-transition">

                    <div id="page-content">
                        <?php echo $this->content; ?>
                        
                    </div><!-- #page-content -->

                </div><!-- #page-content-wrapper -->
            </div><!-- #page-wrapper -->

        </div><!-- #sb-site -->



<div class="sb-slidebar sb-right sb-style-overlay">
<div class="scrollable-content scrollable-nice">
<div class="pad15A">
<a href="#" title="" data-toggle="collapse" data-target="#sidebar-toggle-1" class="popover-title">
    Cloud status
    <span class="caret"></span>
</a>
<div id="sidebar-toggle-1" class="collapse in">
    <div class="pad15A">
        <div class="row">
            <div class="col-md-4">
                <div class="text-center font-gray pad5B text-transform-upr font-size-12">New visits</div>
                <div class="chart-alt-3 font-gray-dark" data-percent="55"><span>55</span>%</div>
            </div>
            <div class="col-md-4">
                <div class="text-center font-gray pad5B text-transform-upr font-size-12">Bounce rate</div>
                <div class="chart-alt-3 font-gray-dark" data-percent="46"><span>46</span>%</div>
            </div>
            <div class="col-md-4">
                <div class="text-center font-gray pad5B text-transform-upr font-size-12">Server load</div>
                <div class="chart-alt-3 font-gray-dark" data-percent="92"><span>92</span>%</div>
            </div>
        </div>
        <div class="divider mrg15T mrg15B"></div>
        <div class="text-center">
            <a href="#" class="btn center-div btn-info mrg5T btn-sm text-transform-upr updateEasyPieChart">
                <i class="glyph-icon icon-refresh"></i>
                Update charts
            </a>
        </div>
    </div>
</div>

<div class="clear"></div>

<a href="#" title="" data-toggle="collapse" data-target="#sidebar-toggle-6" class="popover-title">
    Latest transfers
    <span class="caret"></span>
</a>
<div id="sidebar-toggle-6" class="collapse in">

    <ul class="files-box">
        <li>
            <i class="files-icon glyph-icon font-red icon-file-archive-o"></i>
            <div class="files-content">
                <b>blog_export.zip</b>
                <div class="files-date">
                    <i class="glyph-icon icon-clock-o"></i>
                    added on <b>22.10.2014</b>
                </div>
            </div>
            <div class="files-buttons">
                <a href="#" class="btn btn-xs hover-info tooltip-button" data-placement="right" title="Download">
                    <i class="glyph-icon icon-cloud-download"></i>
                </a>
                <a href="#" class="btn btn-xs hover-danger tooltip-button" data-placement="right" title="Delete">
                    <i class="glyph-icon icon-times"></i>
                </a>
            </div>
        </li>
        <li class="divider"></li>
        <li>
            <i class="files-icon glyph-icon icon-file-code-o"></i>
            <div class="files-content">
                <b>homepage-test.html</b>
                <div class="files-date">
                    <i class="glyph-icon icon-clock-o"></i>
                    added  <b>19.10.2014</b>
                </div>
            </div>
            <div class="files-buttons">
                <a href="#" class="btn btn-xs hover-info tooltip-button" data-placement="right" title="Download">
                    <i class="glyph-icon icon-cloud-download"></i>
                </a>
                <a href="#" class="btn btn-xs hover-danger tooltip-button" data-placement="right" title="Delete">
                    <i class="glyph-icon icon-times"></i>
                </a>
            </div>
        </li>
        <li class="divider"></li>
        <li>
            <i class="files-icon glyph-icon font-yellow icon-file-image-o"></i>
            <div class="files-content">
                <b>monthlyReport.jpg</b>
                <div class="files-date">
                    <i class="glyph-icon icon-clock-o"></i>
                    added on <b>10.9.2014</b>
                </div>
            </div>
            <div class="files-buttons">
                <a href="#" class="btn btn-xs hover-info tooltip-button" data-placement="right" title="Download">
                    <i class="glyph-icon icon-cloud-download"></i>
                </a>
                <a href="#" class="btn btn-xs hover-danger tooltip-button" data-placement="right" title="Delete">
                    <i class="glyph-icon icon-times"></i>
                </a>
            </div>
        </li>
        <li class="divider"></li>
        <li>
            <i class="files-icon glyph-icon font-green icon-file-word-o"></i>
            <div class="files-content">
                <b>new_presentation.doc</b>
                <div class="files-date">
                    <i class="glyph-icon icon-clock-o"></i>
                    added on <b>5.9.2014</b>
                </div>
            </div>
            <div class="files-buttons">
                <a href="#" class="btn btn-xs hover-info tooltip-button" data-placement="right" title="Download">
                    <i class="glyph-icon icon-cloud-download"></i>
                </a>
                <a href="#" class="btn btn-xs hover-danger tooltip-button" data-placement="right" title="Delete">
                    <i class="glyph-icon icon-times"></i>
                </a>
            </div>
        </li>
    </ul>

</div>

<div class="clear"></div>

<a href="#" title="" data-toggle="collapse" data-target="#sidebar-toggle-3" class="popover-title">
    Tasks for today
    <span class="caret"></span>
</a>
<div id="sidebar-toggle-3" class="collapse in">

    <ul class="progress-box">
        <li>
            <div class="progress-title">
                New features development
                <b>87%</b>
            </div>
            <div class="progressbar-smaller progressbar" data-value="87">
                <div class="progressbar-value bg-azure">
                    <div class="progressbar-overlay"></div>
                </div>
            </div>
        </li>
        <li>
            <div class="progress-title">
                Finishing uploading files
                <b>66%</b>
            </div>
            <div class="progressbar-smaller progressbar" data-value="66">
                <div class="progressbar-value bg-red">
                    <div class="progressbar-overlay"></div>
                </div>
            </div>
        </li>
        <li>
            <div class="progress-title">
                Creating tutorials
                <b>58%</b>
            </div>
            <div class="progressbar-smaller progressbar" data-value="58">
                <div class="progressbar-value bg-blue-alt"></div>
            </div>
        </li>
        <li>
            <div class="progress-title">
                Frontend bonus theme
                <b>74%</b>
            </div>
            <div class="progressbar-smaller progressbar" data-value="74">
                <div class="progressbar-value bg-purple"></div>
            </div>
        </li>
    </ul>

</div>

<div class="clear"></div>

<a href="#" title="" data-toggle="collapse" data-target="#sidebar-toggle-4" class="popover-title">
    Pending notifications
    <span class="bs-label bg-orange tooltip-button" title="Label example">New</span>
    <span class="caret"></span>
</a>
<div id="sidebar-toggle-4" class="collapse in">
    <ul class="notifications-box notifications-box-alt">
        <li>
            <span class="bg-purple icon-notification glyph-icon icon-users"></span>
            <span class="notification-text">This is an error notification</span>
            <div class="notification-time">
                a few seconds ago
                <span class="glyph-icon icon-clock-o"></span>
            </div>
            <a href="#" class="notification-btn btn btn-xs btn-black tooltip-button" data-placement="right" title="View details">
                <i class="glyph-icon icon-arrow-right"></i>
            </a>
        </li>
        <li>
            <span class="bg-warning icon-notification glyph-icon icon-ticket"></span>
            <span class="notification-text">This is a warning notification</span>
            <div class="notification-time">
                <b>15</b> minutes ago
                <span class="glyph-icon icon-clock-o"></span>
            </div>
            <a href="#" class="notification-btn btn btn-xs btn-black tooltip-button" data-placement="right" title="View details">
                <i class="glyph-icon icon-arrow-right"></i>
            </a>
        </li>
        <li>
            <span class="bg-green icon-notification glyph-icon icon-random"></span>
            <span class="notification-text font-green">A success message example.</span>
            <div class="notification-time">
                <b>2 hours</b> ago
                <span class="glyph-icon icon-clock-o"></span>
            </div>
            <a href="#" class="notification-btn btn btn-xs btn-black tooltip-button" data-placement="right" title="View details">
                <i class="glyph-icon icon-arrow-right"></i>
            </a>
        </li>
    </ul>
</div>
</div>
</div>
</div>

        <script type="text/javascript" src="<?php echo $this->basePath() ?>/admin/assets-minified/all-demo.js"></script>
        <script type="text/javascript" src="<?php echo $this->basePath() ?>/admin/bootstrap-table/dist/bootstrap-table.js"></script>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
